version: '3.9'

services:
  api:
    build: ./api
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - rabbitmq
      - backup
      # - emails
  backup:
    build: ./backup
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
    ports:
      - 3001:3000
    volumes:
      - ./backup/files:/app/files
    restart: always
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
